#!/bin/bash

# env.js 파일 생성
cat > ./build/env.js << EOF
window._env_ = {
  REACT_APP_OPENAI_API_ENDPOINT: '${REACT_APP_OPENAI_API_ENDPOINT}',
  REACT_APP_OPENAI_MODEL: '${REACT_APP_OPENAI_MODEL}',
  REACT_APP_OPENAI_API_KEY: '${REACT_APP_OPENAI_API_KEY}',
  REACT_APP_SUPABASE_URL: '${REACT_APP_SUPABASE_URL}',
  REACT_APP_SUPABASE_ANON_KEY: '${REACT_APP_SUPABASE_ANON_KEY}',
  REACT_APP_CLAUDE_API_KEY: '${REACT_APP_CLAUDE_API_KEY}',
  REACT_APP_CLOUDMARSSIVE_API_KEY: '${REACT_APP_CLOUDMARSSIVE_API_KEY}',
  REACT_APP_GOOGLE_CLIENT_ID: '${REACT_APP_GOOGLE_CLIENT_ID}',
  REACT_APP_GOOGLE_DRIVE_ROOT_FOLDER_ID: '${REACT_APP_GOOGLE_DRIVE_ROOT_FOLDER_ID}',
  REACT_APP_GOOGLE_DRIVE_SUBFOLDER: '${REACT_APP_GOOGLE_DRIVE_SUBFOLDER}'
};
EOF 