-- 기종 접미사 '-' 통일 (자동생성, 총 110건)
-- Supabase SQL Editor에서 실행하세요

BEGIN;

UPDATE parts SET name = '컨트롤러 - X200프로/X100프로' WHERE id = 576;
UPDATE parts SET name = '컬러 포크가드 스티커 블랙 - X100맥스' WHERE id = 788;
UPDATE parts SET name = '컨트롤러 - 미니' WHERE id = 574;
UPDATE parts SET name = '유성기어 - X200맥스/X100프로/X200프로/X50' WHERE id = 540;
UPDATE parts SET name = '메인 케이블 세트 - X200프로/터보프로/X100프로' WHERE id = 587;
UPDATE parts SET name = '프레임 블랙 - X50' WHERE id = 723;
UPDATE parts SET name = 'cowboy 서스펜션 포크 - X100맥스' WHERE id = 782;
UPDATE parts SET name = '모터 세트 - 터보프로' WHERE id = 578;
UPDATE parts SET name = '메인 케이블 세트 - X50' WHERE id = 612;
UPDATE parts SET name = 'DC 컨버터 - X200프로/터보프로/X100프로' WHERE id = 610;
UPDATE parts SET name = '5인치 헤드라이트 - 레트로20' WHERE id = 1060;
UPDATE parts SET name = '시트포스트 배터리 케이스 - 미니' WHERE id = 682;
UPDATE parts SET name = '컬러 포크가드 스티커 핑크 - X200맥스' WHERE id = 753;
UPDATE parts SET name = '리어 브레이크 세트 - 터보프로' WHERE id = 689;
UPDATE parts SET name = '반사경 세트 - 미니' WHERE id = 678;
UPDATE parts SET name = '프레임 블랙 - X200프로SL' WHERE id = 1263;
UPDATE parts SET name = '알람 시스템 세트(모듈, 리모컨) - X200프로/터보프로/X100프로' WHERE id = 687;
UPDATE parts SET name = '프레임 베이지 - X200프로SL' WHERE id = 1265;
UPDATE parts SET name = 'Cowboy 포크가드 - X200프로SL/X100맥스SL/X50FS' WHERE id = 1260;
UPDATE parts SET name = 'Fastace 디스크 로터 203E 2.3mm - 터보프로' WHERE id = 703;
UPDATE parts SET name = '와이드 시트 - X50' WHERE id = 712;
UPDATE parts SET name = '프론트 엑슬 - 터보프로' WHERE id = 730;
UPDATE parts SET name = '머드가드 세트 - X50' WHERE id = 713;
UPDATE parts SET name = '컬러 사이드렉 세트 블랙 - X200맥스/X100맥스/X200프로' WHERE id = 769;
UPDATE parts SET name = '모터 너트 세트 - X200맥스SL/X100맥스SL/X200프로SL/X50FS' WHERE id = 1223;
UPDATE parts SET name = '컬러 머드가드 세트 레드 - X200맥스' WHERE id = 770;
UPDATE parts SET name = '컬러 사이드렉 세트 블루 - X200맥스/X100맥스/X200프로' WHERE id = 768;
UPDATE parts SET name = '리어렉 - X50' WHERE id = 706;
UPDATE parts SET name = '모터 세트 - X200프로/X100프로' WHERE id = 595;
UPDATE parts SET name = '시트포스트 배터리 - 미니' WHERE id = 572;
UPDATE parts SET name = '프레임 메탈그레이 - X200프로SL' WHERE id = 1264;
UPDATE parts SET name = '프론트 림 - 터보S' WHERE id = 1197;
UPDATE parts SET name = '리어 모터 - 미니' WHERE id = 570;
UPDATE parts SET name = '컨트롤러 - 터보프로' WHERE id = 577;
UPDATE parts SET name = '프론트 모터 - 미니' WHERE id = 571;
UPDATE parts SET name = '프론트 림 - 터보프로' WHERE id = 592;
UPDATE parts SET name = 'KTET 프론트 브레이크 세트 - 레트로/레트로미니' WHERE id = 964;
UPDATE parts SET name = '컨트롤러 - X200GT/X100GT' WHERE id = 1391;
UPDATE parts SET name = '접이식 풋페그(발판) 세트 - 미니' WHERE id = 810;
UPDATE parts SET name = '컬러 포크가드 스티커 블랙 - X200맥스' WHERE id = 755;
UPDATE parts SET name = '프레임 블랙 - X200맥스' WHERE id = 739;
UPDATE parts SET name = '소프트 톨시트 브라운 - X200맥스' WHERE id = 1175;
UPDATE parts SET name = '모터 베어링 - X200맥스/X100맥스/X200프로/X50' WHERE id = 1189;
UPDATE parts SET name = '[카고] 프론트 엑슬 - 카고' WHERE id = 1103;
UPDATE parts SET name = '헤드라이트 - 미니' WHERE id = 568;
UPDATE parts SET name = '헤드라이트 스위치 - X50' WHERE id = 611;
UPDATE parts SET name = '컬러 사이드렉 세트 핑크 - X200맥스/X100맥스/X200프로' WHERE id = 767;
UPDATE parts SET name = '브레이크 센서 - 터보프로' WHERE id = 597;
UPDATE parts SET name = '리어 브레이크 래버 - 터보프로' WHERE id = 684;
UPDATE parts SET name = '머드가드 세트 - 미니' WHERE id = 677;
UPDATE parts SET name = '소프트 숏시트 블랙 - X200맥스' WHERE id = 741;
UPDATE parts SET name = '프론트 브레이크 세트 - 터보프로' WHERE id = 692;
UPDATE parts SET name = '컬러 포크가드 스티커 옐로우 - X100맥스' WHERE id = 785;
UPDATE parts SET name = '시트포스트 클램프 - 미니' WHERE id = 722;
UPDATE parts SET name = '소프트 톨시트 블랙 - X200맥스' WHERE id = 743;
UPDATE parts SET name = '불렛 헤드라이트 - X200프로/터보프로/X100프로' WHERE id = 581;
UPDATE parts SET name = '프론트 엑슬 - X200프로/X100프로/X50' WHERE id = 733;
UPDATE parts SET name = '헤드라이트 링 아답터 - X200프로/터보프로/X100프로' WHERE id = 690;
UPDATE parts SET name = '컨트롤러 - 터보S' WHERE id = 1195;
UPDATE parts SET name = '컬러 포크가드 스티커 옐로우 - X200맥스' WHERE id = 752;
UPDATE parts SET name = '컨트롤러 플레이트 - 터보프로' WHERE id = 735;
UPDATE parts SET name = '컨트롤러 케이스 - 미니' WHERE id = 680;
UPDATE parts SET name = '프론트 포크 - 미니' WHERE id = 669;
UPDATE parts SET name = '컬러 머드가드 세트 옐로우 - X200맥스' WHERE id = 771;
UPDATE parts SET name = '핸들바 - 미니' WHERE id = 671;
UPDATE parts SET name = '스템 - 미니' WHERE id = 672;
UPDATE parts SET name = '풋페그(발판) 세트 - 미니' WHERE id = 667;
UPDATE parts SET name = '컬러 사이드렉 세트 옐로우 - X200맥스/X100맥스/X200프로' WHERE id = 766;
UPDATE parts SET name = '컬러 포크가드 스티커 레드 - X100맥스' WHERE id = 784;
UPDATE parts SET name = '소프트 롱시트 블랙 - X100맥스' WHERE id = 783;
UPDATE parts SET name = '프레임 블랙 - X100맥스' WHERE id = 780;
UPDATE parts SET name = '컬러 머드가드 세트 핑크 - X200맥스' WHERE id = 772;
UPDATE parts SET name = '모터 세트 - 터보S' WHERE id = 1196;
UPDATE parts SET name = 'KKE 브레이크 라인 홀더 - X200프로/터보프로/X50' WHERE id = 734;
UPDATE parts SET name = '배터리 케이블 케이블 - 미니' WHERE id = 589;
UPDATE parts SET name = '접이식 풋페그(유아발판) - X200프로/터보프로/X50' WHERE id = 793;
UPDATE parts SET name = '컬러 포크가드 스티커 블루 - X100맥스' WHERE id = 787;
UPDATE parts SET name = '소프트 숏시트 - X100맥스' WHERE id = 1038;
UPDATE parts SET name = 'DBSM - 터보프로' WHERE id = 586;
UPDATE parts SET name = '프론트 림 - X200프로/X100프로' WHERE id = 591;
UPDATE parts SET name = '컬러 포크가드 스티커 블루 - X200맥스' WHERE id = 754;
UPDATE parts SET name = '릴레이 - X200프로/터보프로/X100프로' WHERE id = 606;
UPDATE parts SET name = '헤드라이트 홀더 - X200프로/터보프로/X100프로' WHERE id = 691;
UPDATE parts SET name = 'DBSM - X200프로' WHERE id = 585;
UPDATE parts SET name = '컬러 머드가드 세트 블랙 - X200맥스' WHERE id = 774;
UPDATE parts SET name = '서클 헤드라이트 - X200프로/터보프로/X100프로' WHERE id = 580;
UPDATE parts SET name = '컬러 포크가드 스티커 레드 - X200맥스' WHERE id = 751;
UPDATE parts SET name = '컬러 사이드렉 세트 레드 - X200맥스/X100맥스/X200프로' WHERE id = 765;
UPDATE parts SET name = '프론트 브레이크 세트 XOD - 미니' WHERE id = 673;
UPDATE parts SET name = '리어 브레이크 세트 XOD - 미니' WHERE id = 674;
UPDATE parts SET name = '튜브리스 타이어 1개 - 미니' WHERE id = 681;
UPDATE parts SET name = '수납가방 - 미니' WHERE id = 679;
UPDATE parts SET name = '리어렉(짐받이) - 미니' WHERE id = 666;
UPDATE parts SET name = '배터리 젠더 케이블 - 미니' WHERE id = 575;
UPDATE parts SET name = '리어 서스펜션 - 미니' WHERE id = 668;
UPDATE parts SET name = 'KKE 프론트 유압 포크 - X200MAX/X100MAX/X200프로/터보프로/X50' WHERE id = 695;
UPDATE parts SET name = '킥스탠드 - 미니' WHERE id = 670;
UPDATE parts SET name = '메인 케이블 세트 - 미니' WHERE id = 573;
UPDATE parts SET name = '다용도 바스켓 - 미니' WHERE id = 811;
UPDATE parts SET name = '프론트 브레이크 래버 - 터보프로' WHERE id = 683;
UPDATE parts SET name = '스윙암 피봇 세트 - X200맥스' WHERE id = 1227;
UPDATE parts SET name = 'KKE 포크가드 세트 - X200프로/터보프로/X50' WHERE id = 708;
UPDATE parts SET name = '컬러 머드가드 세트 블루 - X200맥스' WHERE id = 773;
UPDATE parts SET name = '프론트 림 베어링 세트 - X200맥스/X100맥스/X200프로/X50' WHERE id = 1188;
UPDATE parts SET name = '컬러 포크가드 스티커 핑크 - X100맥스' WHERE id = 786;
UPDATE parts SET name = '소프트 롱시트 블랙 - X200맥스' WHERE id = 742;
UPDATE parts SET name = '소프트 숏시트 브라운 - X200맥스' WHERE id = 1176;
UPDATE parts SET name = '소프트 롱시트 브라운 - X200맥스' WHERE id = 1174;
UPDATE parts SET name = '방향지시등(윙카) 세트 - X200프로/터보프로/X100프로' WHERE id = 582;
UPDATE parts SET name = '컨트롤러 - X50' WHERE id = 613;

COMMIT;
