[build]
  command = "npm install && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "9"
  REACT_APP_OPENAI_MODEL = "gpt-4o-mini"
  NODE_ENV = "production"
  REACT_APP_BACKEND_URL = "https://crm-production-067b.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_OPENAI_MODEL = "gpt-4o-mini" 